# Default configuration for Augur Reference Implementation
server:
  host: "0.0.0.0"
  port: 8080

bitcoinRpc:
  url: "http://localhost:8332"
  username: ""
  password: ""

persistence:
  dataDirectory: "mempool_data"
  # Number of days to retain mempool data files (0 = disabled, keep indefinitely)
  retentionDays: 0
