# Default configuration for Augur Reference Implementation
server:
  host: "0.0.0.0"
  port: 8080

bitcoinRpc:
  url: "http://localhost:8332"
  username: ""
  password: ""

persistence:
  dataDirectory: "mempool_data"
  cleanupDays: 0  # Set to 0 to disable cleanup, or number of days to retain files
